[package]
name = "crates-index-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crates-index = { version = "=2.5.0", features = [ "git-https" ] }
